/**
 * init.ts — bootstrap .hackathon/ inside the current repo.
 *
 * Creates:
 *   .hackathon/skills/   (bundled skills copied from this repo)
 *   .hackathon/state/    (empty JSON files matching schemas)
 *   .hackathon/artifacts/ (empty)
 *
 * Refuses to overwrite an existing .hackathon/ unless --force.
 */

import { existsSync, mkdirSync, cpSync, writeFileSync, readFileSync } from "node:fs";
import { resolve, join, dirname } from "node:path";

import { log } from "../lib/logger.js";

function findPackageRoot(): string {
  // Walk up from this file until we find package.json.
  let dir = dirname(new URL(import.meta.url).pathname);
  for (let i = 0; i < 8; i++) {
    if (existsSync(join(dir, "package.json"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

const PACKAGE_ROOT = findPackageRoot();

const STATE_FILES = [
  "plan.json",
  "verify.json",
  "demo.json",
  "review.json",
  "ship.json",
];

export interface InitOptions {
  cwd: string;
  force?: boolean;
}

export function init(opts: InitOptions): number {
  const target = resolve(opts.cwd, ".hackathon");
  if (existsSync(target) && !opts.force) {
    log.err(`.hackathon/ already exists at ${target}. Use --force to overwrite.`);
    return 1;
  }

  mkdirSync(join(target, "state"), { recursive: true });
  mkdirSync(join(target, "artifacts"), { recursive: true });

  // Copy bundled skills if available.
  const skillsSrc = join(PACKAGE_ROOT, "skills");
  const skillsDst = join(target, "skills");
  if (existsSync(skillsSrc)) {
    cpSync(skillsSrc, skillsDst, { recursive: true });
    log.ok(`copied bundled skills to ${skillsDst}`);
  } else {
    log.warn(`bundled skills not found at ${skillsSrc}; skipping copy`);
  }

  // Seed empty state files (each is valid JSON matching its schema).
  for (const f of STATE_FILES) {
    const stub = f === "plan.json"
      ? { version: "1.0", generated_at: new Date().toISOString(),
          demo_goal: "", time_remaining_minutes: 0,
          features: [], demo_path: [], next_tasks: [] }
      : f === "verify.json"
      ? { version: "1.0", steps: [], status: "pending" }
      : f === "demo.json"
      ? { version: "1.0", duration_seconds: 60, steps: [] }
      : f === "review.json"
      ? { version: "1.0", dimensions: [], overall: 0 }
      : { version: "1.0", checks: [], status: "pending" };
    writeFileSync(join(target, "state", f), JSON.stringify(stub, null, 2));
  }
  log.ok(`seeded ${STATE_FILES.length} state files`);

  // Drop a marker.
  writeFileSync(
    join(target, "INIT_NOTE.txt"),
    "Generated by Hackathon Surgeon. Edit freely — these files are yours.\n",
  );

  log.ok(`.hackathon/ initialized at ${target}`);
  log.dim("Next: hackathon run scope-knife");
  return 0;
}
