/**
 * init.ts — bootstrap .hackathon/ inside the current repo.
 *
 * Creates:
 *   .hackathon/skills/   (bundled skills copied from this repo)
 *   .hackathon/state/    (5 canonical flow files seeded; optional skills create the rest)
 *   .hackathon/artifacts/ (empty)
 *
 * Refuses to overwrite an existing .hackathon/ unless --force.
 *
 * UX:
 *   - Prints a banner with the absolute target path BEFORE any write.
 *   - In a TTY, prompts for confirmation unless --yes is passed.
 *   - In a non-TTY (CI, piped output), refuses to run without --yes
 *     to avoid silent side effects.
 *   - --dry-run prints the plan and exits 0 without writing.
 */

import { existsSync, mkdirSync, writeFileSync, readdirSync, copyFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { createInterface } from 'node:readline';

import { log } from '../lib/logger.js';
import { findPackageRoot } from '../../harness/package-root.js';
import { buildSkeleton } from './run.js';
import { defaultSession, writeSession } from '../../harness/session.js';

function copyDirSync(src: string, dst: string): void {
  mkdirSync(dst, { recursive: true });
  for (const entry of readdirSync(src, { withFileTypes: true })) {
    const s = join(src, entry.name);
    const d = join(dst, entry.name);
    if (entry.isDirectory()) copyDirSync(s, d);
    else copyFileSync(s, d);
  }
}
const PACKAGE_ROOT = findPackageRoot();

const STATE_FILES = ['plan.json', 'verify.json', 'demo.json', 'review.json', 'ship.json'];

export interface InitOptions {
  cwd: string;
  force?: boolean;
  yes?: boolean;
  dryRun?: boolean;
}

async function confirm(message: string): Promise<boolean> {
  if (!process.stdin.isTTY) return false;
  return new Promise((resolvePrompt) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(`${message} [y/N] `, (answer) => {
      rl.close();
      resolvePrompt(/^y(es)?$/i.test(answer.trim()));
    });
  });
}

export async function init(opts: InitOptions): Promise<number> {
  const target = resolve(opts.cwd, '.hackathon');
  const root = resolve(opts.cwd);

  // Banner first — show what we will do before any side effect.
  log.bold('hackathon init');
  log.dim(`  target:  ${target}`);
  log.dim(
    `  source:  ${PACKAGE_ROOT ? join(PACKAGE_ROOT, 'skills') : '(package root not found — skills will be skipped)'}`,
  );
  log.dim(`  state:   ${STATE_FILES.length} JSON files in .hackathon/state/`);

  if (existsSync(target)) {
    if (!opts.force) {
      log.err(`.hackathon/ already exists at ${target}. Use --force to overwrite.`);
      return 1;
    }
    log.warn(`existing .hackathon/ at ${target} will be overwritten`);
  }

  if (opts.dryRun) {
    log.ok('dry-run: no files written');
    return 0;
  }

  // Gate side effects behind an explicit confirmation when we have a chance to ask.
  if (process.stdin.isTTY && !opts.yes) {
    const ok = await confirm('Proceed?');
    if (!ok) {
      log.warn('aborted by user');
      return 0;
    }
  } else if (!opts.yes) {
    log.err('non-interactive mode requires --yes (or use --dry-run to preview)');
    return 2;
  }

  mkdirSync(join(target, 'state'), { recursive: true });
  mkdirSync(join(target, 'artifacts'), { recursive: true });
  mkdirSync(join(target, 'traces'), { recursive: true });

  // Copy bundled skills if available.
  const skillsSrc = PACKAGE_ROOT ? join(PACKAGE_ROOT, 'skills') : null;
  const skillsDst = join(target, 'skills');
  if (skillsSrc && existsSync(skillsSrc)) {
    copyDirSync(skillsSrc, skillsDst);
    log.ok(`copied bundled skills to ${skillsDst}`);
  } else {
    log.warn(
      'bundled skills source not found; skipping copy. ' +
        'Run from inside the npm package, or set HACKATHON_RUN_HOME.',
    );
  }

  // Seed empty state files (each is valid JSON matching its schema).
  for (const f of STATE_FILES) {
    const stub = buildSkeleton(f, { skillName: f });
    writeFileSync(join(target, 'state', f), JSON.stringify(stub, null, 2));
  }
  log.ok(`seeded ${STATE_FILES.length} state files`);

  const session = defaultSession(root);
  writeSession(root, session);
  writeFileSync(
    join(target, 'SESSION.md'),
    [
      '# Hackathon Run Session',
      '',
      `Generated: ${session.generated_at}`,
      '',
      '## Current stage',
      '',
      session.current_stage,
      '',
      '## Next task',
      '',
      session.next_task,
      '',
      '## Handoff rule',
      '',
      'A fresh agent should read SESSION.md, state/plan.json, and state/session.json before doing anything.',
      '',
    ].join('\n'),
    'utf8',
  );

  // Drop a marker.
  writeFileSync(
    join(target, 'INIT_NOTE.txt'),
    'Generated by Hackathon Run. Edit freely — these files are yours.\n',
  );

  log.ok(`.hackathon/ initialized at ${target}`);
  log.dim('Next: hackathon run scope-knife, then hackathon resume');
  return 0;
}
