/**
 * report.ts — generate a post-hackathon markdown report from state files.
 *
 * The report is the "what did we actually do" artifact: it turns the
 * state in .hackathon/state/ into a timeline, stage-by-stage highlights,
 * quality gates (verify / demo / review / ship), and a final verdict.
 * Teams can drop it into a README or a blog post minutes after the demo.
 *
 * Usage:
 *   hackathon report                     # print markdown to stdout
 *   hackathon report --out REPORT.md     # write to a file
 *   hackathon report --json              # machine-readable
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve, basename, extname } from 'node:path';

import { collectTimeline } from './replay.js';
import { readTraces } from '../../harness/trace.js';
import { c } from '../lib/colors.js';
import { log } from '../lib/logger.js';

export interface ReportOptions {
  cwd?: string;
  out?: string;
  json?: boolean;
}

const PKG_VERSION: string =
  JSON.parse(readFileSync(new URL('../../../package.json', import.meta.url), 'utf8')).version ??
  '0.6.0';

function safeJson(file: string): Record<string, any> | null {
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
}

function countClass(features: any[], cls: string): number {
  return Array.isArray(features) ? features.filter((f) => f && f.classification === cls).length : 0;
}

function renderMarkdown(
  root: string,
  stateDir: string,
  files: string[],
  data: Map<string, Record<string, any>>,
  traceEvents: ReturnType<typeof readTraces>,
): string {
  const lines: string[] = [];
  const plan = data.get('plan.json');
  const verdict = verdictOf(data);

  lines.push('# Hackathon report');
  lines.push('');
  lines.push(`- **Generated:** ${new Date().toISOString()}`);
  lines.push(`- **Repo root:** \`${root}\``);
  lines.push(`- **State dir:** \`${stateDir}\``);
  if (plan?.demo_goal) {
    lines.push(`- **Demo goal:** ${plan.demo_goal}`);
  }
  lines.push('');

  if (verdict) {
    lines.push(`> **Verdict: ${verdict.label}** — ${verdict.note}`);
    lines.push('');
  }

  const roster = data.get('roster.json');
  if (roster && Array.isArray(roster.members) && roster.members.length > 0) {
    lines.push('## Team');
    lines.push('');
    for (const m of roster.members) {
      const blocker = m.blocker ? ` (stuck: ${m.blocker})` : '';
      lines.push(`- **${m.name}** — ${m.role}${blocker}`);
    }
    if (roster.bottleneck?.member) {
      lines.push('');
      lines.push(`**Bottleneck:** ${roster.bottleneck.member} — ${roster.bottleneck.reason ?? ''}`);
    }
    lines.push('');
  }

  if (plan && Array.isArray(plan.features) && plan.features.length > 0) {
    lines.push('## Scope');
    lines.push('');
    const keep = countClass(plan.features, 'KEEP');
    const cut = countClass(plan.features, 'CUT');
    const defer = countClass(plan.features, 'DEFER');
    lines.push(`- **KEEP:** ${keep}`);
    lines.push(`- **CUT:** ${cut}`);
    lines.push(`- **DEFER:** ${defer}`);
    lines.push('');
  }

  lines.push('## Timeline');
  lines.push('');

  if (traceEvents.length > 0) {
    const byType = traceEvents.reduce<Record<string, number>>((acc, e) => {
      acc[e.type] = (acc[e.type] ?? 0) + 1;
      return acc;
    }, {});
    lines.push('## Harness trace');
    lines.push('');
    lines.push(`- **Events:** ${traceEvents.length}`);
    for (const [type, count] of Object.entries(byType)) {
      lines.push(`- \`${type}\`: ${count}`);
    }
    lines.push('');
  }
  lines.push('| T+ | File | Highlight |');
  lines.push('| --- | --- | --- |');
  const sorted = [...data.entries()].sort((a, b) => {
    const ta = Date.parse(a[1].generated_at ?? a[1].started_at ?? a[1].finished_at ?? '') || 0;
    const tb = Date.parse(b[1].generated_at ?? b[1].started_at ?? b[1].finished_at ?? '') || 0;
    return ta - tb;
  });
  const t0 =
    sorted.length > 0
      ? Date.parse(sorted[0][1].generated_at ?? sorted[0][1].started_at ?? '') || 0
      : 0;
  for (const [file, json] of sorted) {
    const ts = Date.parse(json.generated_at ?? json.started_at ?? json.finished_at ?? '') || 0;
    const offset = t0 ? `+${Math.max(0, Math.round((ts - t0) / 60000))}m` : 'start';
    lines.push(`| ${offset} | \`${file}\` | ${highlightOf(file, json)} |`);
  }
  lines.push('');

  for (const file of files.sort()) {
    const json = data.get(file);
    if (!json) continue;
    const section = sectionOf(file, json);
    if (!section) continue;
    lines.push(`## ${titleOf(file)}`);
    lines.push('');
    lines.push(section);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`_Report generated by \`hackathon report\` (v${PKG_VERSION})._`);
  lines.push('');
  return lines.join('\n');
}

function titleOf(file: string): string {
  const stem = basename(file, extname(file));
  const map: Record<string, string> = {
    plan: 'Plan',
    verify: 'Verification',
    demo: 'Demo script',
    review: 'Judge review',
    ship: 'Ship audit',
    recovery: 'Recovery runbook',
    'time-box': 'Time budget',
    stack: 'Stack decision',
    retro: 'Retrospective',
    rehearsal: 'Demo rehearsal',
    roster: 'Roster',
    sprint: 'Sprint contract',
    eval: 'Evaluator verdict',
    session: 'Session handoff',
  };
  return map[stem] ?? stem;
}

function highlightOf(file: string, json: Record<string, any>): string {
  const stem = basename(file, extname(file));
  switch (stem) {
    case 'plan':
      return json.demo_goal ?? '(no goal)';
    case 'verify':
      return `status=${json.status ?? '?'}, ${(json.steps ?? []).length} steps`;
    case 'demo':
      return `${json.duration_seconds ?? '?'}s, ${(json.steps ?? []).length} steps`;
    case 'review':
      return `overall=${json.overall ?? '?'}/5, ${(json.dimensions ?? []).length} dimensions`;
    case 'ship':
      return `secret scan clean=${json.secret_scan?.clean ?? '?'}, checklist ${(json.checklist?.passed ?? []).length}/${(json.checklist?.passed ?? []).length + (json.checklist?.failed ?? []).length}`;
    case 'recovery':
      return `severity=${json.severity ?? '?'}`;
    case 'retro':
      return `scope accuracy=${json.ratios?.scope_accuracy ?? '?'}`;
    case 'roster':
      return `${json.team_size ?? '?'} members, bottleneck=${json.bottleneck?.member ?? 'none'}`;
    case 'rehearsal':
      return `run #${json.run_number ?? '?'}, verdict=${json.verdict ?? '?'}`;
    case 'time-box':
      return `${json.time_remaining_minutes ?? '?'}min, stage=${json.current_stage ?? '?'}`;
    case 'stack':
      return json.recommendation?.stack ?? '?';
    case 'sprint':
      return `${json.name ?? '?'} [${json.status ?? '?'}] ${
        (json.criteria ?? []).filter((c: any) => c.passes).length
      }/${(json.criteria ?? []).length} criteria`;
    case 'eval':
      return `${json.verdict ?? '?'} ${
        (json.criteria ?? []).filter((c: any) => c.passes).length
      }/${(json.criteria ?? []).length} criteria`;
    case 'session':
      return `${json.current_stage ?? '?'}: ${json.next_task ?? ''}`;
    default:
      return '(parsed)';
  }
}

function sectionOf(file: string, json: Record<string, any>): string {
  const stem = basename(file, extname(file));
  const bullets: string[] = [];
  switch (stem) {
    case 'verify':
      if (Array.isArray(json.steps)) {
        for (const s of json.steps) {
          bullets.push(`- ${s.command ?? s.action ?? '(step)'} — ${s.status ?? s.result ?? '?'}`);
        }
      }
      break;
    case 'demo':
      if (Array.isArray(json.steps)) {
        for (const s of json.steps) {
          bullets.push(`- ${s.name ?? s.action ?? '(step)'} — ${s.say ?? ''}`);
        }
      }
      break;
    case 'review':
      if (Array.isArray(json.dimensions)) {
        for (const d of json.dimensions) {
          bullets.push(
            `- **${d.name}:** ${d.score ?? '?'}/5 — ${(d.deduction_reason ?? '').slice(0, 80)}`,
          );
        }
      }
      break;
    case 'ship':
      for (const item of json.checklist?.passed ?? []) bullets.push(`- [x] ${item}`);
      for (const item of json.checklist?.failed ?? []) bullets.push(`- [ ] ${item}`);
      break;
    case 'recovery':
      bullets.push(`- **Failure:** ${json.failure ?? '?'}`);
      bullets.push(`- **Severity:** ${json.severity ?? '?'}`);
      break;
    case 'retro':
      for (const item of json.keep_doing ?? []) bullets.push(`- Keep: ${item}`);
      for (const item of json.stop_doing ?? []) bullets.push(`- Stop: ${item}`);
      for (const item of json.try_next_time ?? []) bullets.push(`- Try: ${item}`);
      break;
    case 'roster':
      if (Array.isArray(json.members)) {
        for (const m of json.members) {
          bullets.push(`- **${m.name}** — ${m.role} (${m.status ?? 'ok'})`);
        }
      }
      break;
    case 'rehearsal':
      if (Array.isArray(json.fixes)) {
        for (const f of json.fixes) {
          bullets.push(
            `- Step ${f.step}: cut "${f.cut}", keep "${f.keep}" (new budget ${f.new_budget_seconds}s)`,
          );
        }
      }
      break;
    case 'time-box':
      if (Array.isArray(json.schedule)) {
        for (const s of json.schedule) {
          bullets.push(`- ${s.stage ?? '?'}: ${s.work_minutes ?? s.minutes ?? '?'}min`);
        }
      }
      break;
    case 'stack':
      bullets.push(`- **Recommended:** ${json.recommendation?.stack ?? '?'}`);
      for (const r of json.runners_up ?? []) {
        bullets.push(`- Runner-up: ${r.stack ?? r}`);
      }
      break;
    case 'sprint':
      for (const criterion of json.criteria ?? []) {
        const mark = criterion.passes ? 'x' : ' ';
        bullets.push(`- [${mark}] ${criterion.id}: ${criterion.description}`);
      }
      for (const item of json.feedback ?? []) bullets.push(`- Feedback: ${item}`);
      break;
    case 'eval':
      for (const criterion of json.criteria ?? []) {
        const mark = criterion.passes ? 'x' : ' ';
        bullets.push(`- [${mark}] ${criterion.id}: ${criterion.description}`);
        if (typeof criterion.score === 'number') bullets.push(`  - Score: ${criterion.score}/5`);
        for (const evidence of criterion.evidence ?? []) {
          bullets.push(`  - ${evidence.kind}: ${evidence.value}`);
        }
      }
      if (json.strategy) bullets.push(`- **Strategy:** ${json.strategy}`);
      for (const item of json.feedback ?? []) bullets.push(`- Feedback: ${item}`);
      for (const dimension of json.rubric?.dimensions ?? []) {
        bullets.push(
          `- **Rubric:** ${dimension.name ?? dimension.id ?? '?'} (weight ${dimension.weight ?? 0}, threshold ${dimension.threshold ?? 0})`,
        );
      }
      break;
    case 'session':
      bullets.push(`- **Stage:** ${json.current_stage ?? '?'}`);
      bullets.push(`- **Next:** ${json.next_task ?? '?'}`);
      for (const item of json.blockers ?? []) bullets.push(`- Blocker: ${item}`);
      break;
    default:
      return '';
  }
  return bullets.length > 0 ? bullets.join('\n') : '_no details captured_';
}

function verdictOf(data: Map<string, Record<string, any>>): { label: string; note: string } | null {
  const ship = data.get('ship.json');
  const review = data.get('review.json');
  const verify = data.get('verify.json');
  const clean = ship?.secret_scan?.clean !== false;
  const checklistEmpty =
    Array.isArray(ship?.checklist?.failed) && ship.checklist.failed.length === 0;
  const reviewScore = typeof review?.overall === 'number' ? review.overall : null;
  const verified =
    verify?.status === 'passed' || (Array.isArray(verify?.steps) && verify.steps.length > 0);
  if (clean && checklistEmpty && reviewScore != null && reviewScore >= 4 && verified) {
    return {
      label: 'SHIP READY',
      note: 'All gates green: secrets clean, checklist empty, judge score strong.',
    };
  }
  if (reviewScore != null && reviewScore < 3) {
    return {
      label: 'NEEDS WORK',
      note: 'Judge simulation scored below 3/5; prioritize fix_now items.',
    };
  }
  if (ship && !clean) {
    return {
      label: 'BLOCKED ON SECRETS',
      note: 'Ship audit found secret-scan findings; fix before submitting.',
    };
  }
  if (!verified) {
    return {
      label: 'UNVERIFIED',
      note: 'No passing verify.json; run fast-verify before the demo.',
    };
  }
  return null;
}

export function report(opts: ReportOptions): number {
  const cwd = opts.cwd ?? process.cwd();
  let collected: ReturnType<typeof collectTimeline>;
  try {
    collected = collectTimeline(cwd);
  } catch (e) {
    log.err((e as Error).message);
    log.dim(`run ${c.cyan('hackathon init')} first`);
    return 2;
  }
  const stateDir = collected.stateDir;
  const files = readdirSync(stateDir)
    .filter((f) => f.endsWith('.json'))
    .sort();
  const data = new Map<string, Record<string, any>>();
  const traceEvents = readTraces(cwd);
  for (const f of files) {
    const json = safeJson(join(stateDir, f));
    if (json) data.set(f, json);
  }

  if (opts.json) {
    const payload = {
      repo_root: cwd,
      state_dir: stateDir,
      generated_at: new Date().toISOString(),
      verdict: verdictOf(data),
      states: Object.fromEntries(data),
      trace: {
        count: traceEvents.length,
        events: traceEvents.slice(-100),
      },
    };
    console.log(JSON.stringify(payload, null, 2));
    return 0;
  }

  const markdown = renderMarkdown(cwd, stateDir, files, data, traceEvents);
  if (opts.out) {
    const target = resolve(opts.out);
    writeFileSync(target, markdown, 'utf8');
    log.ok(`wrote ${target}`);
    return 0;
  }
  console.log(markdown);
  return 0;
}
